

import { Toaster } from "@/components/ui/toaster"
import AuthProvider from "@/context/AuthProviders";
import '../globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <AuthProvider>
        <html lang="en">
            <body>
                
                {children}  
                <Toaster /> 
            </body>
        </html>
    </AuthProvider>   
  )
}
